version: 2


defaults:
  release_filter: &release_filter
    filters:
      tags:
        only: /^release-.*/
      branches:
        ignore: /.*/

  master_commits: &master_commits
    filters:
      branches:
        only:
          - master


jobs:
  deploy_cui_browser_image:
     working_directory: ~/build
     docker:
       - image: docker:17.05.0-ce
     steps:
       - checkout
       - setup_remote_docker
       - run:
           name: Deploy cui-browser docker image
           command: |
             docker build -t build/cui-browser -f ./devops/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker tag build/cui-browser cybernode/cui-browser:$CIRCLE_TAG
             docker push cybernode/cui-browser:$CIRCLE_TAG
             docker tag build/cui-browser cybernode/cui-browser:latest
             docker push cybernode/cui-browser:latest

workflows:
  version: 2

  ui_build:
    jobs:
      - deploy_cui_browser_image:
          <<: *master_commits
