version: 2


defaults:
  release_filter: &release_filter
    filters:
      tags:
        only: /^release-.*/
      branches:
        ignore: /.*/


jobs:
  deploy_image:
     working_directory: ~/build
     docker:
       - image: docker:17.05.0-ce-git
     steps:
       - checkout
       - setup_remote_docker
       - run:
           name: Build docker image
           command: |
             docker build -t build/cui-browser -f ./devops/Dockerfile ./
             docker login -u $DOCKER_USER -p $DOCKER_PASS
       - deploy:
           name: Upload :latest image to DockerHub
           command: |
             # $CIRCLE_TAG is not set when building for `master`
             #docker tag build/cui-browser cybernode/cui-browser:$CIRCLE_TAG
             #docker push cybernode/cui-browser:$CIRCLE_TAG
             docker tag build/cui-browser cybernode/cui-browser:latest
             docker push cybernode/cui-browser:latest

workflows:
  version: 2

  ui_build_deploy:
    jobs:
      - deploy_image:
          filters:
            branches:
              only: master
