version: '3.3'
services:


  chaingear-api:
    image: cybernode/chaingear-api:latest
    ports:
      - 32600:8090
    environment:
      ADV_HOST: chaingear-api

  cn-exchange-stream-api:
    image: cybernode/cm-stream-api:latest
    ports:
      - "32801:18080"
    environment:
      KAFKA_CONNECTION: kafka:9092
    labels:
      kompose.service.type: loadbalancer

  cm-rest-api:
    image: cybernode/cm-rest-api:latest
    ports:
      - "32800:8085"
    labels:
      kompose.service.type: loadbalancer

  cm-connector-bitstamp:
    container_name: cm-connector-bitstamp
    image: cybernode/cm-connectors-bitstamp:latest
    environment:
      KAFKA_CONNECTION: kafka:9092

  cm-connectors-hitbtc:
    container_name: cm-connectors-hitbtc
    image: cybernode/cm-connectors-hitbtc:latest
    environment:
      KAFKA_CONNECTION: kafka:9092

  cm-connectors-poloniex:
    container_name: cm-connectors-poloniex
    image: cybernode/cm-connectors-poloniex:latest
    environment:
      KAFKA_CONNECTION: kafka:9092

  cm-connectors-bitfinex:
    container_name: cm-connectors-bitfinex
    image: cybernode/cm-connectors-bitfinex:latest
    environment:
      KAFKA_CONNECTION: kafka:9092

  cm-tickers:
    container_name: cm-tickers
    image: cybernode/cm-tickers:latest
    environment:
      KAFKA_CONNECTION: kafka:9092
      WINDOW_DURATIONS_MIN: 1
      WINDOW_HOP_SEC: 5
