version: '3.3'
services:

  elassandra:
    container_name: elassandra
    image: strapdata/elassandra:5.5.0.8
    restart: always
    volumes:
      - /cyberdata/staging/elassandra/lib:/var/lib/cassandra
      - /cyberdata/staging/elassandra/log:/var/log/cassandra
    environment:
      CASSANDRA_DC: DEVELOPMENT
      CASSANDRA_CLUSTER_NAME: CYBER_SEARCH
    ports:
      - "9042:9042"
      - "9200:9200"
      - "9300:9300"

  zoo:
    container_name: zoo
    restart: always
    image: confluentinc/cp-zookeeper:4.0.0
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
    volumes:
      - /cyberdata/staging/zoo/data:/var/lib/zookeeper/data
      - /cyberdata/staging/zoo/log:/var/lib/zookeeper/log
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    restart: always
    image: confluentinc/cp-kafka:4.0.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_JMX_PORT: 1099
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - /cyberdata/staging/kafka:/var/lib/kafka
    ports:
      - "9092:9092"
      - "1099:1099"

  kafka-manager:
    container_name: kafka-manager
    image: hlebalbau/kafka-manager:1.3.3.15
    restart: always
    environment:
      ZK_HOSTS: "zoo:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null
    ports:
      - 9000:9000
