version: '3.3'
services:

  cyber-ui:
    image: cybernode/cui-browser:latest
    ports:
      - 32500:80
    environment:
      CYBER_CHAINGEAR_API: http://staging.cyber.fund:32600
      CYBER_SEARCH_API: http://192.168.0.119:10300
      CYBER_MARKETS_API: http://staging.cyber.fund:32800

  cs-chain-pumps-btc:
    container_name: pump-btc
    image: cybernode/cs-chain-pumps:latest
    restart: on-failure
    environment:
      CASSANDRA_HOSTS: elassandra
      CS_CHAINS_TO_PUMP: BITCOIN
      BITCOIND_URL: http://cyber:cyber@bitcoind:8332
      CS_LOG_LEVEL: INFO

  cs-chain-pumps-bth:
    container_name: pump-bth
    image: cybernode/cs-chain-pumps:latest
    restart: on-failure
    environment:
      CASSANDRA_HOSTS: elassandra
      CS_CHAINS_TO_PUMP: BITCOIN_CASH
      ABC_URL: http://bitcoin:password@abc:18332
      CS_LOG_LEVEL: INFO

#  cs-chain-pumps-eth:
#    container_name: pump-eth
#    image: cybernode/cs-chain-pumps:latest
#    restart: on-failure
#    environment:
#      CASSANDRA_HOSTS: elassandra
#      CS_CHAINS_TO_PUMP: ETHEREUM
#      PARITY_ETH_URL: http://parity_eth:8545
#      CS_LOG_LEVEL: INFO
#
#  cs-chain-pumps-etc:
#    container_name: pump-etc
#    image: cybernode/cs-chain-pumps:latest
#    restart: on-failure
#   environment:
#      CS_CHAINS_TO_PUMP: ETHEREUM_CLASSIC
#      PARITY_ETC_URL: http://parity_etc:18545
#      CASSANDRA_HOSTS: elassandra
#      CS_LOG_LEVEL: INFO

  cs-search-api:
    container_name: search-api
    ports:
      - 10300:10300
    image: cybernode/cs-search-api:latest
    restart: on-failure
    environment:
      CASSANDRA_HOSTS: elassandra
      CS_LOG_LEVEL: INFO
      CORS_ALLOWED_ORIGINS: "*"

  cs-address-service:
    container_name: address-service
    image: cybernode/address-service:latest
    restart: on-failure
    environment:
      CASSANDRA_HOSTS: elassandra
      KAFKA_BROKERS: kafka:9092
      CS_LOG_LEVEL: INFO
